travis:
  secure:
    BINSTAR_TOKEN: hexND3ml/B0+D+RWogy+z9yKsMNyYYs76FzLu6r8EhF3cTe8oKa1kPfzvlpQ26Z3EuAK4VuNUGDsXkohz5w4mAHbb3eRGbrVc25u2Ri6OnChlTVGdcJ/6lIh8Tc7/J4VPZjy115a+IdMQkyY/WKDuuYy4L4YYRZKHymVdFeeLNVHT+0WUj6ROVC/nTlNbU991h+WKHDaa2ccuGXM4VJi6sYr3+LNPu0iYNZFehUPrmG2ICxRhY3jckg/dt7fmYMahvEJzp84M7wEiGJTMF/oBWPbYEjAg+yoDRGvsQwQyIopdn8zB3n16lFtm+AjjBrvfw3LxXeY952NupD/wC2qe3B06pBMQGwZs2Fu64uEcvZ0zWaSrhkoLqS7CPTW7RwA4wnMH502GssyZT8qdfm927BRKnuB9eWIDbAeERvIV4UIIg7bMmayWSZm8gxqiFD3lriTOIyJ0nIhh7s7nL+kI22BPA7qu68Cvm85ZakkeUYEklsFv9agK+t4Fj8NkqgNSYOEkhNaL4lYVFerszpP/6JGdjRjEWePBKRH09S6CMHJ5pJcnNpOYApMEPum40wUTNPpk+pPR2nb/YTlremyXT+AaYL3GkNRKon+2kr/qTiI9YfFlbSXfAdI5te2WrvHFYKH+Zls3buwFdvg0dxGmULwcrQdWEcF1TXrWzG8v70=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
